
-- add modes: debug and release 
add_rules("mode.debug", "mode.release")

-- add target
target("butterworth-filter")

    -- set kind
    set_kind("binary")

    -- add files
    add_files("src/*.cpp")
    add_includedirs("D:/Develop/libs/boost_1_61_0")
    add_includedirs("D:/Develop/DL/libs/opencv-3.4.2-vs2015x64-qt/include")
    add_includedirs("D:/Develop/DL/libs/PCL-1.8/include/pcl-1.8")
    add_includedirs("C:/Program Files/VTK/include/vtk-8.1")
    add_includedirs("D:/Develop/DL/libs/Eigen3/include/eigen3")
    add_includedirs("D:/Develop/DL/libs/flann/include")
    add_includedirs("D:/Develop/DL/libs/qhull/include")
    add_links("vtkalglib-8.1")
    add_links("vtkChartsCore-8.1")
    add_links("vtkCommonColor-8.1")
    add_links("vtkCommonComputationalGeometry-8.1")
    add_links("vtkCommonCore-8.1")
    add_links("vtkCommonDataModel-8.1")
    add_links("vtkCommonExecutionModel-8.1")
    add_links("vtkCommonMath-8.1")
    add_links("vtkCommonMisc-8.1")
    add_links("vtkCommonSystem-8.1")
    add_links("vtkCommonTransforms-8.1")
    add_links("vtkDICOMParser-8.1")
    add_links("vtkDomainsChemistry-8.1")
    add_links("vtkDomainsChemistryOpenGL2-8.1")
    add_links("vtkexoIIc-8.1")
    add_links("vtkexpat-8.1")
    add_links("vtkFiltersAMR-8.1")
    add_links("vtkFiltersCore-8.1")
    add_links("vtkFiltersExtraction-8.1")
    add_links("vtkFiltersFlowPaths-8.1")
    add_links("vtkFiltersGeneral-8.1")
    add_links("vtkFiltersGeneric-8.1")
    add_links("vtkFiltersGeometry-8.1")
    add_links("vtkFiltersHybrid-8.1")
    add_links("vtkFiltersHyperTree-8.1")
    add_links("vtkFiltersImaging-8.1")
    add_links("vtkFiltersModeling-8.1")
    add_links("vtkFiltersParallel-8.1")
    add_links("vtkFiltersParallelImaging-8.1")
    add_links("vtkFiltersPoints-8.1")
    add_links("vtkFiltersProgrammable-8.1")
    add_links("vtkFiltersSelection-8.1")
    add_links("vtkFiltersSMP-8.1")
    add_links("vtkFiltersSources-8.1")
    add_links("vtkFiltersStatistics-8.1")
    add_links("vtkFiltersTexture-8.1")
    add_links("vtkFiltersTopology-8.1")
    add_links("vtkFiltersVerdict-8.1")
    add_links("vtkfreetype-8.1")
    add_links("vtkGeovisCore-8.1")
    add_links("vtkgl2ps-8.1")
    add_links("vtkglew-8.1")
    add_links("vtkGUISupportQt-8.1")
    add_links("vtkGUISupportQtOpenGL-8.1")
    add_links("vtkGUISupportQtSQL-8.1")
    add_links("vtkGUISupportQtWebkit-8.1")
    add_links("vtkhdf5-8.1")
    add_links("vtkhdf5_hl-8.1")
    add_links("vtkImagingColor-8.1")
    add_links("vtkImagingCore-8.1")
    add_links("vtkImagingFourier-8.1")
    add_links("vtkImagingGeneral-8.1")
    add_links("vtkImagingHybrid-8.1")
    add_links("vtkImagingMath-8.1")
    add_links("vtkImagingMorphological-8.1")
    add_links("vtkImagingSources-8.1")
    add_links("vtkImagingStatistics-8.1")
    add_links("vtkImagingStencil-8.1")
    add_links("vtkInfovisCore-8.1")
    add_links("vtkInfovisLayout-8.1")
    add_links("vtkInteractionImage-8.1")
    add_links("vtkInteractionStyle-8.1")
    add_links("vtkInteractionWidgets-8.1")
    add_links("vtkIOAMR-8.1")
    add_links("vtkIOCore-8.1")
    add_links("vtkIOEnSight-8.1")
    add_links("vtkIOExodus-8.1")
    add_links("vtkIOExport-8.1")
    add_links("vtkIOExportOpenGL2-8.1")
    add_links("vtkIOGeometry-8.1")
    add_links("vtkIOImage-8.1")
    add_links("vtkIOImport-8.1")
    add_links("vtkIOInfovis-8.1")
    add_links("vtkIOLegacy-8.1")
    add_links("vtkIOLSDyna-8.1")
    add_links("vtkIOMINC-8.1")
    add_links("vtkIOMovie-8.1")
    add_links("vtkIONetCDF-8.1")
    add_links("vtkIOParallel-8.1")
    add_links("vtkIOParallelXML-8.1")
    add_links("vtkIOPLY-8.1")
    add_links("vtkIOSQL-8.1")
    add_links("vtkIOTecplotTable-8.1")
    add_links("vtkIOVideo-8.1")
    add_links("vtkIOXML-8.1")
    add_links("vtkIOXMLParser-8.1")
    add_links("vtkjpeg-8.1")
    add_links("vtkjsoncpp-8.1")
    add_links("vtklibharu-8.1")
    add_links("vtklibxml2-8.1")
    add_links("vtklz4-8.1")
    add_links("vtkmetaio-8.1")
    add_links("vtkNetCDF-8.1")
    add_links("vtknetcdfcpp-8.1")
    add_links("vtkoggtheora-8.1")
    add_links("vtkParallelCore-8.1")
    add_links("vtkpng-8.1")
    add_links("vtkproj4-8.1")
    add_links("vtkRenderingAnnotation-8.1")
    add_links("vtkRenderingContext2D-8.1")
    add_links("vtkRenderingContextOpenGL2-8.1")
    add_links("vtkRenderingCore-8.1")
    add_links("vtkRenderingFreeType-8.1")
    add_links("vtkRenderingGL2PSOpenGL2-8.1")
    add_links("vtkRenderingImage-8.1")
    add_links("vtkRenderingLabel-8.1")
    add_links("vtkRenderingLOD-8.1")
    add_links("vtkRenderingOpenGL2-8.1")
    add_links("vtkRenderingParallel-8.1")
    add_links("vtkRenderingQt-8.1")
    add_links("vtkRenderingVolume-8.1")
    add_links("vtkRenderingVolumeOpenGL2-8.1")
    add_links("vtksqlite-8.1")
    add_links("vtksys-8.1")
    add_links("vtktiff-8.1")
    add_links("vtkverdict-8.1")
    add_links("vtkViewsContext2D-8.1")
    add_links("vtkViewsCore-8.1")
    add_links("vtkViewsInfovis-8.1")
    add_links("vtkViewsQt-8.1")
    add_links("vtkWebCore-8.1")
    add_links("vtkWebGLExporter-8.1")
    add_links("vtkzlib-8.1")
    add_links("opencv_aruco342")
    add_links("opencv_bgsegm342")
    add_links("opencv_bioinspired342")
    add_links("opencv_calib3d342")
    add_links("opencv_ccalib342")
    add_links("opencv_core342")
    add_links("opencv_cudaarithm342")
    add_links("opencv_cudabgsegm342")
    add_links("opencv_cudacodec342")
    add_links("opencv_cudafeatures2d342")
    add_links("opencv_cudafilters342")
    add_links("opencv_cudaimgproc342")
    add_links("opencv_cudalegacy342")
    add_links("opencv_cudaobjdetect342")
    add_links("opencv_cudaoptflow342")
    add_links("opencv_cudastereo342")
    add_links("opencv_cudawarping342")
    add_links("opencv_cudev342")
    add_links("opencv_datasets342")
    add_links("opencv_dnn342")
    add_links("opencv_dnn_objdetect342")
    add_links("opencv_dpm342")
    add_links("opencv_face342")
    add_links("opencv_features2d342")
    add_links("opencv_flann342")
    add_links("opencv_freetype342")
    add_links("opencv_fuzzy342")
    add_links("opencv_hdf342")
    add_links("opencv_hfs342")
    add_links("opencv_highgui342")
    add_links("opencv_imgcodecs342")
    add_links("opencv_imgproc342")
    add_links("opencv_img_hash342")
    add_links("opencv_line_descriptor342")
    add_links("opencv_ml342")
    add_links("opencv_objdetect342")
    add_links("opencv_optflow342")
    add_links("opencv_phase_unwrapping342")
    add_links("opencv_photo342")
    add_links("opencv_plot342")
    add_links("opencv_reg342")
    add_links("opencv_rgbd342")
    add_links("opencv_saliency342")
    add_links("opencv_sfm342")
    add_links("opencv_shape342")
    add_links("opencv_stereo342")
    add_links("opencv_stitching342")
    add_links("opencv_structured_light342")
    add_links("opencv_superres342")
    add_links("opencv_surface_matching342")
    add_links("opencv_text342")
    add_links("opencv_tracking342")
    add_links("opencv_video342")
    add_links("opencv_videoio342")
    add_links("opencv_videostab342")
    add_links("opencv_viz342")
    add_links("opencv_xfeatures2d342")
    add_links("opencv_ximgproc342")
    add_links("opencv_xobjdetect342")
    add_links("opencv_xphoto342")
    add_links("dlib_release_64bit_msvc1900")
    add_links("freeglut")
    add_links("glew64")
    add_links("pcl_common_release")
    add_links("pcl_cuda_features_release")
    add_links("pcl_cuda_sample_consensus_release")
    add_links("pcl_cuda_segmentation_release")
    add_links("pcl_features_release")
    add_links("pcl_filters_release")
    add_links("pcl_gpu_containers_release")
    add_links("pcl_gpu_features_release")
    add_links("pcl_gpu_kinfu_large_scale_release")
    add_links("pcl_gpu_kinfu_release")
    add_links("pcl_gpu_octree_release")
    add_links("pcl_gpu_people_release")
    add_links("pcl_gpu_segmentation_release")
    add_links("pcl_gpu_surface_release")
    add_links("pcl_gpu_tracking_release")
    add_links("pcl_gpu_utils_release")
    add_links("pcl_io_ply_release")
    add_links("pcl_io_release")
    add_links("pcl_kdtree_release")
    add_links("pcl_keypoints_release")
    add_links("pcl_ml_release")
    add_links("pcl_octree_release")
    add_links("pcl_outofcore_release")
    add_links("pcl_people_release")
    add_links("pcl_recognition_release")
    add_links("pcl_registration_release")
    add_links("pcl_sample_consensus_release")
    add_links("pcl_search_release")
    add_links("pcl_segmentation_release")
    add_links("pcl_simulation_io_release")
    add_links("pcl_simulation_release")
    add_links("pcl_stereo_release")
    add_links("pcl_surface_release")
    add_links("pcl_tracking_release")
    add_links("pcl_visualization_release")
    add_links("boost_atomic-vc140-mt-1_61")
    add_links("boost_filesystem-vc140-mt-1_61")
    add_links("boost_chrono-vc140-mt-1_61")
    add_links("boost_container-vc140-mt-1_61")
    add_links("boost_context-vc140-mt-1_61")
    add_links("boost_coroutine-vc140-mt-1_61")
    add_links("boost_date_time-vc140-mt-1_61")
    -- add_links("boost_exception-vc140-mt-1_61")
    add_links("boost_filesystem-vc140-mt-1_61")
    add_links("boost_graph-vc140-mt-1_61")
    add_links("boost_iostreams-vc140-mt-1_61")
    add_links("boost_locale-vc140-mt-1_61")
    add_links("boost_log_setup-vc140-mt-1_61")
    add_links("boost_log-vc140-mt-1_61")
    add_links("boost_math_c99f-vc140-mt-1_61")
    add_links("boost_math_c99l-vc140-mt-1_61")
    add_links("boost_math_c99-vc140-mt-1_61")
    add_links("boost_math_tr1f-vc140-mt-1_61")
    add_links("boost_math_tr1l-vc140-mt-1_61")
    add_links("boost_math_tr1-vc140-mt-1_61")
    -- add_links("boost_mpi-vc140-mt-1_61")
    add_links("boost_prg_exec_monitor-vc140-mt-1_61")
    add_links("boost_program_options-vc140-mt-1_61")
    add_links("boost_random-vc140-mt-1_61")
    add_links("boost_regex-vc140-mt-1_61")
    add_links("boost_serialization-vc140-mt-1_61")
    add_links("boost_signals-vc140-mt-1_61")
    add_links("boost_system-vc140-mt-1_61")
    -- add_links("boost_test_exec_monitor-vc140-mt-1_61")
    add_links("boost_thread-vc140-mt-1_61")
    add_links("boost_timer-vc140-mt-1_61")
    add_links("boost_type_erasure-vc140-mt-1_61")
    -- add_links("boost_unit_test_framework-vc140-mt-1_61")
    add_links("boost_wave-vc140-mt-1_61")
    add_links("boost_wserialization-vc140-mt-1_61")
    add_linkdirs("D:/Develop/DL/libs/PCL-1.8/lib")
    add_linkdirs("D:/Develop/DL/libs/opencv-3.4.2-vs2015x64-qt/x64/vc14/lib")
    add_linkdirs("C:/local/boost_1_61_0/lib64-msvc-14.0")
    add_linkdirs(" C:/Program Files/VTK/lib")
   
--
-- FAQ
--
-- You can enter the project directory firstly before building project.
--   
--   $ cd projectdir
-- 
-- 1. How to build project?
--   
--   $ xmake
--
-- 2. How to configure project?
--
--   $ xmake f -p [macosx|linux|iphoneos ..] -a [x86_64|i386|arm64 ..] -m [debug|release]
--
-- 3. Where is the build output directory?
--
--   The default output directory is `./build` and you can configure the output directory.
--
--   $ xmake f -o outputdir
--   $ xmake
--
-- 4. How to run and debug target after building project?
--
--   $ xmake run [targetname]
--   $ xmake run -d [targetname]
--
-- 5. How to install target to the system directory or other output directory?
--
--   $ xmake install 
--   $ xmake install -o installdir
--
-- 6. Add some frequently-used compilation flags in xmake.lua
--
-- @code 
--    -- add macro defination
--    add_defines("NDEBUG", "_GNU_SOURCE=1")
--
--    -- set warning all as error
--    set_warnings("all", "error")
--
--    -- set language: c99, c++11
--    set_languages("c99", "cxx11")
--
--    -- set optimization: none, faster, fastest, smallest 
--    set_optimize("fastest")
--    
--    -- add include search directories
--    add_includedirs("/usr/include", "/usr/local/include")
--
--    -- add link libraries and search directories
--    add_links("tbox", "z", "pthread")
--    add_linkdirs("/usr/local/lib", "/usr/lib")
--
--    -- add compilation and link flags
--    add_cxflags("-stdnolib", "-fno-strict-aliasing")
--    add_ldflags("-L/usr/local/lib", "-lpthread", {force = true})
--
-- @endcode
--
-- 7. If you want to known more usage about xmake, please see http://xmake.io/#/home
--
    
